name: "fetch-tfstate"
description: "Fetch Terraform Cloud tfstate on GitHub Actions"
inputs:
  terraform-cloud-token:
    description: "Terraform Cloud token (Team API Token assumed)"
    required: true
  workspace-id:
    description: "Terraform Cloud workspace ID"
    required: true
  path-to-tfstate:
    description: "Path to the tfstate file"
    required: false
outputs:
  tfstate:
    description: "Terraform Cloud tfstate"
    value: ${{ steps.fetch-tfstate.outputs.tfstate-path }}
runs:
  using: "composite"
  steps:
    - name: Fetch Terraform Cloud tfstate
      id: fetch-tfstate
      run: |
        set -euo pipefail
        HTTP_RESPONSE=$(curl \
          --header "Authorization: Bearer "${{ inputs.terraform-cloud-token }}"" \
          --header "Content-Type: application/vnd.api+json" \
          "https://app.terraform.io/api/v2/workspaces/${{ inputs.workspace-id }}/current-state-version" | jq -r '.data | .attributes | ."hosted-state-download-url"')
        TFSTATE_FILE=${{ inputs.path-to-tfstate }}
        if [ -z "${TFSTATE_FILE}" ]; then
          TFSTATE_FILE=$(mktemp)
        fi
        curl -o $TFSTATE_FILE $HTTP_RESPONSE
        echo "tfstate-path=${TFSTATE_FILE}" >> $GITHUB_OUTPUT
      shell: bash
